# Generated by Django 5.0.6 on 2024-06-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('style', models.TextField(default='')),
                ('other_style', models.CharField(blank=True, max_length=100, null=True)),
                ('bedroom_image', models.ImageField(default='static/images/bedroom1.jpg', upload_to='static/images')),
                ('hall_image', models.ImageField(default='static/images/hall1.jpg', upload_to='static/images')),
                ('dining_room_image', models.ImageField(default='static/images/dining_room1.jpg', upload_to='static/images')),
                ('kitchen_image', models.ImageField(default='static/images/kitchen1.jpg', upload_to='static/images')),
                ('bathroom_image', models.ImageField(default='static/images/bathroom1.jpg', upload_to='static/images')),
                ('facade_image', models.ImageField(default='static/images/facade.jpg', upload_to='static/images')),
                ('studio_image', models.ImageField(default='static/images/studio1.jpg', upload_to='static/images')),
                ('wood_images', models.JSONField(blank=True, null=True)),
                ('pcolor_image', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
