# Generated by Django 5.0.6 on 2024-06-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='wood_images',
            field=models.ImageField(default='static/images/wood1.jpg', upload_to='static/images'),
        ),
    ]
